# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bee544442afc737a3d2a02be2e33a2430850eadf13fc8fbf8ca433cbf09fc99759558b861b4094cac85d15ae090b4e2039e8128413cf4686836180412d152e8

test:
  secret_key_base: 572349ad53e31c443435a4c0aa161ceea473c6c2858f5a05692fa080729fa1c3a708a435d97af68b118070aaf1ad0b4e3025f02730381f4c0276d6c5c0cb2bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
